version: '3.8'
services:
  be:
    build: qrcoder-be
    container_name: qrcoder-be
    ports:
      - "8080:8080"
  db:
    build: qrcoder-db
    container_name: qrcoder-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./dbdata/data:/var/lib/postgresql/data
